### PR TITLE
Add zh_Hans & zh_Hant languages to Button

### PR DESCRIPTION
**Pull request by ArcticFoxPro**
Add zh_Hans & zh_Hant languages to Button.

The type family uses `Noto Sans`.

### CODE REVIEW

**Comment by Songyon** [comment]
Oh, I forgot to mention that I'm giving Button to add the Chinese language.

**Comment by razzeee** [comment]
This is not the correct way to do this IMO.

You should just translate the strings in https://hosted.weblate.org/projects/flathub/frontend/ and the backend should automatically render it.

**Comment by ArcticFoxPro** [comment]
> This is not the correct way to do this IMO.
> 
> You should just translate the strings in https://hosted.weblate.org/projects/flathub/frontend/ and the backend should automatically render it.

Thanks for your help. But I think my PR is the Chinese version of your Svg download badges. Can this backend be rendered as well?

**Comment by razzeee** [comment]
Yeah, ideally, this should be removed from the repo and maybe add a textfile pointing at https://flathub.org/badges

**Comment by ArcticFoxPro** [comment]
OK，I see, I will close this PR immediately.

**Comment by ArcticFoxPro** [comment]
> Yeah, ideally, this should be removed from the repo and maybe add a textfile pointing at https://flathub.org/badges

I found out https://flathub.org/badges is no localization of simplified Chinese, but traditional Chinese is localized. How can I upload my local svg that I can contribute my pin to you? because https://hosted.weblate.org/projects/flathub/frontend/ is no character string associated with it.

**Comment by razzeee** [comment]
The string is called `get-it-on`, there is no SVG, we're creating those on the server on the fly

**Pull request closed without merging**
