### PR TITLE
buttons: resize to a more usable 240x80px

### LINKED ISSUE #1595: Badges are scaled by default
Right now the PNGs and SVGs for the badges are provided at 300px (or 299px in some cases?) wide, but we recommend (in the code samples) scaling them to 240px wide.

We should provide the assets at a more appropriate size by default:

- 240px for PNG
  - Possibly 480px for 2x/HiDPI scaling
- 240px wide for SVG to not need to explicitly scale client-side

### PR DESCRIPTION
**Pull request by jimmac**
Fixes https://github.com/flathub/website/issues/1595

### CODE REVIEW

**Comment by razzeee** [comment]
The font in the preview svg button seems broken (yes, I think it was broken even before?)

**Comment by jimmac** [comment]
The SVG in this case is the 'source'. I could convert the text into paths, for you to see it properly without having the appropriate font installed, but that would render the 'source' pointless'.

**Comment by razzeee** [comment]
> The SVG in this case is the 'source'. I could convert the text into paths, for you to see it properly without having the appropriate font installed, but that would render the 'source' pointless'.

Right, was just confused, cause the other font in the svg works :)

**Comment by razzeee** [comment]
@barthalion please add replacing these on the mirrors to your todo list

**Pull request merged**
